### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by luc-ky-khuu** [lkhuu96/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] query for the car 
- [x] add event listeners for keydown for each key
- [x] rotate car towards the direction of the key that was pressed
- [x] make sure car stops turning when facing the direction of the key when pressed or when user releases the key.
- [x] test each arrow key to make sure car turns as intended
